### ISSUE TITLE
[feat] /configuration implementation

### ISSUE THREAD

**Issue by lgrd** [IGNF/road2#37]
### Need

/configuration route is not implemented in the administration API. This route allow an administrator to get the configuration of road2 administrator and to modify it. 

### Tasks

- [x] Delete onStart feature. See #48 
- [x] Allow verification and creation of an administrator without any services. See #51 
- [x] Allow verification and creation and publication of a service without any resources and/or sources. See #47 
- [x] Code  GET /configuration. See #59 
- [ ] Code PATCH /configuration. See #104 
- [ ] Update doc (ex. functionalities, changelog)
- [ ] Update tests (new classes if there are; rtest for this route)
- [ ] Run tests inside docker (rtest, ctest, utest, itest)
