### ISSUE TITLE
[feat] /services/{service}/restart implementation

### ISSUE THREAD

**Issue by lgrd** [IGNF/road2#45]
### Need

Actually, there is no restart route for a service. But it could be useful in different cases. For instance, now, it is easy to add and the other admin routes are not available. But in the future, if you have a problem with a specific route, a restart could be useful. 

### Tasks

- [x] Update API [doc](https://github.com/IGNF/road2/blob/develop/documentation/apis/administration/1.0.0/api.yaml) to be sure of the IO (ex. GET or POST, responses if ok or not). 
- [x] Code it (see next paragrah)
- [x] Update doc (ex. functionalities, changelog)
- [x] Update tests (new classes if there are; rtest for this route)
- [x] Test memory leaks? Tested manually, but an issue where created to investigate it in a more detailed way. See #57 
- [x] Run tests inside docker (rtest, ctest, utest, itest)

### Code 

- Add the route inside the router of the admin API
- Create a function inside the administrator to handle this restart 
- Create a function inside the serviceManager to stop and load the service (this is the restart)
- Create the same function inside administeredService and its child classes (serviceProcess and serviceInsider) to stop the service. The function to load the service has already been written. 
  - serviceInsider : call to this._serviceInstance.stopAllServers() and this._serviceInstance = null to let the garbage collector take it
  - serviceProcess : send a kill via this._serviceInstance.kill(), and this._serviceInstance = null to let the garbage collector take it
- Modify service.initIPC() to add a process.on('SIGKILL') which call this.stopAllServers()
