### ISSUE TITLE
[fix] Analyse memory issues

### ISSUE THREAD

**Issue by lgrd** [IGNF/road2#57]
### Need 

See if there are memory issues. 

### Tasks

- [ ] Apply methods described here : 
  - https://nodejs.org/en/docs/guides/diagnostics/memory 
  - https://nodejs.org/en/docs/guides/diagnostics/memory/using-gc-traces
- [ ] Add some tests inside the project
- [ ] Update the doc to indicate how to test memory issues
