### ISSUE TITLE
[feat] Renvoyer du (e)WKT

### ISSUE THREAD

**Issue by lgrd** [IGNF/road2#6]
# Feature

L'API simple/1.0.0 renvoie des géométries en geojson ou polyline. Mais ces deux formats ne permettent pas de profiter de la reprojection. L'idée est de proposer le [WKT](https://www.ogc.org/standards/ct) pour qu'elle ait du sens. 

# Todo

- [x] Lire les spécifications
- [x] Analyser et lister les devs en délimitant le périmètre
- [x] Créer un module dans le code et comparer les résultats/performances avec l'ancien
- [x] Si performant, remplacer les usages de smartroutingSource.js 
- [x] Ajouter la valeur wkt dans la conf docker de road2 et r2gg
- [x] Modifier les classes du dossier geometry pour utiliser ce nouveau module

**Comment by lgrd** [comment]
En GeoJSON, Road2 n'aurait qu'à gérer : point, linestring, polygon dans une Feature ou une FeatureCollection, potentiellement en 3D. 
En WKT, Road2 n'aurait donc qu'à gérer : point, linestring, polygon, potentiellement dans une geometryCollection, potentiellement en 3D.

**Comment by lgrd** [comment]
Le module est fait pour la conversion des ewkt vers geojson. Et les geojson sortant sont validés par https://www.itb.ec.europa.eu/json/geojson/upload.
