### ISSUE TITLE
[feat] Add all OSRM features

### ISSUE THREAD

**Issue by lgrd** [IGNF/road2#62]
### Need 

Today, Road2 can handle route and nearest requests. But OSRM can compute more than these. So, because we have the motor and the data, we could use all the functionalities of OSRM : table, match, trip and tile. 

### Tasks 

- [ ] Update the API documentation 
- [ ] Add table operation
- [ ] Add match operation
- [ ] Add trip operation
- [ ] Add tile operation (maybe in a debug part of Road2)
