### ISSUE TITLE
[doc] Translate documentation in english

### ISSUE THREAD

**Issue by lgrd** [IGNF/road2#74]
### Need 

Translate all the documentation directory and readme.md in english. 

### Tasks 

- [x] Create a branch from develop
- [x] Translate readme.md but keep the french file
- [x] Translate all the documentation directory keeping the french part. 
- [ ] Update the english readme with a link to the french one
- [ ] Update the CI for the doc generation : see if we can choose between french and english

**Comment by lgrd** [comment]
Finally, the documentation will be in French by default (for laws). But their is a link to read it in English.
