### ISSUE TITLE
[github] Move on YAML issue form

### ISSUE THREAD

**Issue by lgrd** [IGNF/road2#79]
We have some templates written in markdown but we could use the YAML form when it will be a stable feature of Github. 

### Tasks 

- [ ] Wait for the stable version of [issue form](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms) 
- [ ] Translate issue templates for Road2
- [ ] Translate issue templates for r2gg
- [ ] Translate issue templates for Pgr
