### ISSUE TITLE
[github] Add a code of conduct

### ISSUE THREAD

**Issue by lgrd** [IGNF/road2#80]
### Need 

This project and its friends don't have a code of conduct. The idea is to add such a code based on this guide : https://opensource.guide/code-of-conduct/. 

### Tasks

- [x] Write a code of conduct 
- [x] Validation of the team
- [x] Push to road2
- [x] Push to r2gg
- [x] Push to Pgr
