### ISSUE TITLE
[github] Add contributing docs

### ISSUE THREAD

**Issue by lgrd** [IGNF/road2#82]
### Need

This project and its friends don't have a contributing guide. The idea is to add such a guide.

### Tasks

- [x] Write a contributing.md
- [x] Validation of the team
- [x] Push to road2
- [x] Push to r2gg
- [x] Push to Pgr
